services:
  api:
    build: ./backend
    environment:
      API_HOST: ${API_HOST}
      API_PORT: ${API_PORT}
      DEMO_MODE: ${DEMO_MODE}
      GTFS_SQLITE_PATH: ${GTFS_SQLITE_PATH}
    ports:
      - "8000:8000"
    volumes:
      - ./backend/data:/data

  web:
    build: ./frontend
    environment:
      WEB_HOST: ${WEB_HOST}
      WEB_PORT: ${WEB_PORT}
      API_BASE: http://api:8000
      FLASK_ENV: ${FLASK_ENV}
      SECRET_KEY: ${SECRET_KEY}
    ports:
      - "5000:5000"
    depends_on:
      - api